### ISSUE TITLE
Problem when cordova add plugin cordova-plugin-ms-outlook

### ISSUE THREAD

**Issue by erickbarbosa** [OfficeDev/cordova-plugin-ms-outlook#5]
When the installation is in progress, an error occurs in the "cordova-plugin-ms-office-rest-client" config, stack is shown below.

Error: Failed to fetch plugin https://github.com/MSOpenTech/cordova-plugin-ms-office-rest-client.git#0.2.x via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /tmp/npm-5852-4ab1e3a1/git-cache-2e9b6871/05d89bfb009e3f931251d07264f68131cf8ae23a
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/MSOpenTech/cordova-plugin-ms-office-rest-client.git#0.2.x" "--save"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

**Comment by erickbarbosa** [comment]
Maybe needs change url plugin  https://github.com/MSOpenTech/cordova-plugin-ms-office-rest-client.git#0.2.x to  https://github.com/OfficeDev/cordova-plugin-ms-office-rest-client.git#0.2.x
.

**Comment by erickbarbosa** [comment]
I Solved Issue by downgrading cordova from 7.0.X to 6.5.0, but now I got the same error of [Issue 3](https://github.com/OfficeDev/cordova-plugin-ms-outlook/issues/3)

**Comment by Vivekguptaji** [comment]
getting error during add plugin  tried wth both suggested url

D:\Vivek Gupta\Learn\2020\heloo>cordova plugin add https://github.com/MSOpenTec
/cordova-plugin-ms-office-rest-client.git#0.2.x
Failed to fetch plugin https://github.com/MSOpenTech/cordova-plugin-ms-office-r
st-client.git#0.2.x via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\VIVGUP~1\AppData\Local\Temp\npm-42
96-670d9201\git-cache-f6825347\05d89bfb009e3f931251d07264f68131cf8ae23a
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vivgupta5\\AppD
ta\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github
com/MSOpenTech/cordova-plugin-ms-office-rest-client.git#0.2.x" "--production" "
-save"
npm ERR! node v8.12.0
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Vivek Gupta\Learn\2020\heloo\npm-debug.log
